service: lex-bot-deployment

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lex:*'
      Resource: '*'

resources:
  Resources:
    LexBot:
      Type: "AWS::Lex::Bot"
      Properties:
        Name: ${file(src/callbackPhoneNumberUpdate/Bot.json):name}
        Description: ${file(src/callbackPhoneNumberUpdate/Bot.json):description}
        IdleSessionTTLInSeconds: ${file(src/callbackPhoneNumberUpdate/Bot.json):idleSessionTTLInSeconds}
        RoleArn: "arn:aws:iam::750344256621:role/aws-service-role/lexv2.amazonaws.com/AWSServiceRoleForLexV2Bots_lex-bot-deployment-test-role"
        DataPrivacy: 
          ChildDirected: ${file(src/callbackPhoneNumberUpdate/Bot.json):dataPrivacy.childDirected}
    LexBotLocale:
      Type: "AWS::Lex::BotLocale"
      Properties:
        BotId: ${file(src/callbackPhoneNumberUpdate/Bot.json):botId}
        LocaleId: ${file(src/callbackPhoneNumberUpdate/BotLocales/en_US/BotLocale.json):localeId}
        Description: ${file(src/callbackPhoneNumberUpdate/BotLocales/en_US/BotLocale.json):description}
    LexBotIntent:
      Type: "AWS::Lex::BotIntent"
      Properties:
        BotId: ${file(src/callbackPhoneNumberUpdate/Bot.json):botId}
        IntentId: ${file(src/callbackPhoneNumberUpdate/BotLocales/en_US/Intents/FallbackIntent/Intent.json):intentId}
        Description: ${file(src/callbackPhoneNumberUpdate/BotLocales/en_US/Intents/FallbackIntent/Intent.json):description}